### ISSUE TITLE
seed

### ISSUE THREAD

**Issue by shift-reality** [DavidQChuang/TerrainGenerator#1]
hi
what seed are you using for water generation?
Because i see just green plane with seed 22.....
Or something broken on my side?

**Comment by DavidQChuang** [comment]
Sorry, that was an issue I fixed but forgot to upload. It should work now.

**Comment by shift-reality** [comment]
thanks you

**Comment by DavidQChuang** [comment]
If you're interested in using this, you can change the generation parameters at line 49 of Visualization/DemoViewer.java (float dampness, float flatness, float highness). By the way, this is a side project that isn't really that complete. The complete version is elsewhere as part of a private C# project. Could I ask what you're using this for? I may be able to help you more than this project could.
